server:
    port: 8080

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/undergraduatejob?useUnicode=true
        username: lyx
        password: 123
    mail:
        host: smtp.163.com
        username: 18216308307@163.com
        password: m4gewo
        default-encoding: UTF-8
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
    thymeleaf:
        mode: HTML
        encoding: UTF-8
        servlet:
            content-type: text/html
        cache: false
        suffix: .html
        prefix: classpath:/templates/
    redis:
        host: localhost
        port: 6379
        jedis:
            pool:
                max-wait: 30000
                max-active: 100
                max-idle: 20
                min-idle: 0
        timeout: 5000
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
mail:
    queue:
        name: local.mail.queue
    exchange:
        name: local.mail.exchange
    routing:
        key:
            name: local.mail.routing.key


want:
    mail:
        senderName: 59tongChneg
mybatis:

    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
    tokenHeader: Authorization
    secret: mySecret
    expiration: 604800
    tokenHead: Bearer
