server:
    port: 8083

spring:
    datasource:
        url: jdbc:mysql://localhost:3306/undergraduatejob?useUnicode=true
        username: root
        password: 123
    mail:
        host: smtp.163.com
        username: 18216308307@163.com
        password: m4gewo
        default-encoding: UTF-8
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
                        required: true
    thymeleaf:
        mode: HTML
        encoding: UTF-8
        servlet:
            content-type: text/html
        cache: false
        suffix: .html
        prefix: classpath:/templates/
    redis:
        host: 172.16.5.204
        port: 6379
        password: peony_redis
        maxActive: 300
        maxIdle: 100
        maxWait: 50000
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
mail:
    queue:
        name: local.mail.queue
    exchange:
        name: local.mail.exchange
    routing:
        key:
            name: local.mail.routing.key
elasticSearch:
    host: 127.0.0.1
    port: 9200
    client:
        connectNum: 10
        connectPerRoute: 50
#reptile:
#    queue:
#        image-name: local.image.queue
#        job-name: local.job.queue
#        welfare-name: local.welfare.queue
#    exchange:
#        image-name: local.image.exchange
#        job-name: local.job.exchange
#        welfare-name: local.welfare.exchange
#    routing:
#        key:
#            image-name: local.image.routing.key
#            job-name: local.job.routing.key
#            welfare-name: local.welfare.routing.key


want:
    mail:
        senderName: renwen2020
mybatis:

    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
    tokenHeader: Authorization
    secret: mySecret
    expiration: 604800
    tokenHead: Bearer
